---
name: Niagara 4.10   
version: 4.10
slug: niagara4
description: Building Management System
url: https://github.com/nkthurman/addon-tridn4
ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: mdi:sitemap
init: false
arch:
  - amd64
image: nkthurman/tridn4  
ports:
  8443/tcp: 8443
  4911/tcp: 4911
  5011/tcp: 5011
ports_description:
  8443/tcp: Web interface
  4911/tcp: Platform interface
  5011/tcp: Platform interface
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
auth_api: true
apparmor: false
map:
  - config:rw
  - ssl
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  init_commands: []
  http_node:
    username: str
    password: password
  http_static:
    username: str
    password: password
  ssl: bool
  certfile: str
  keyfile: str
